Fix exports (#371)
* fix(throwerror): fix throwerror.ts file name

* fix(exports): fix missing .js extensions in includes and ignoreelements

* chore(dependencies): update dependencies

* fix(exports): make top-level exports match the directory names

* fix lint

* add node v22.x to CI matrix

* remove esm from the build

* don't redirect stderr to /dev/null

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,14 +10,15 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        node: [16.x, 18.x, 20.x]
+        node: [16.x, 18.x, 20.x, 22.x]
         target: [es5, es2015, esnext]
         module: [cjs, esm, umd]
         include:
           - {node: 16.x, target: ix}
           - {node: 18.x, target: ix}
           - {node: 20.x, target: ix}
-          - {node: 20.x, target: src, args: --coverage}
+          - {node: 22.x, target: ix}
+          - {node: 22.x, target: src, args: --coverage}
     steps:
       - name: Setup node v${{ matrix.node }}
         uses: actions/setup-node@v4
@@ -98,6 +99,8 @@ jobs:
           t: "${{ matrix.target }}"
           m: "${{ matrix.module }}"
         run: |
+          set -e;
+
           targetdir="./targets${t:+/${t}}${m:+/${m}}";
           pkg_name="$(jq -r '.name' "${targetdir}/package.json")";
           pkg_type="$(jq -r '.type' "${targetdir}/package.json")";
@@ -108,16 +111,50 @@ jobs:
           cd "${_tmp}/node_modules/${pkg_name}";
           npm i;
           cd "${_tmp}/";
+
+          import_paths=(
+            "${pkg_name}"
+            "${pkg_name}/Ix"
+            "${pkg_name}/Ix.iterable"
+            "${pkg_name}/Ix.iterable.operators"
+            "${pkg_name}/Ix.asynciterable"
+            "${pkg_name}/Ix.asynciterable.operators"
+            "${pkg_name}/iterable/index"
+            "${pkg_name}/iterable/operators"
+            "${pkg_name}/iterable/operators/index"
+            "${pkg_name}/asynciterable/index"
+            "${pkg_name}/asynciterable/operators"
+            "${pkg_name}/asynciterable/operators/index"
+          );
+
+          test_import_esm() {
+            local path;
+            for path in "${import_paths[@]}"; do
+              node --input-type=module -e "import '${path}'";
+            done
+          }
+
+          test_import_cjs() {
+            local path;
+            for path in "${import_paths[@]}"; do
+              node --input-type=commonjs -e "require('${path}')";
+            done
+          }
+
           set -x;
           if test "${pkg_type}" = "module"; then
             # Test importing as ESModule
-            node --input-type=module -e "import '${pkg_name}'";
+            test_import_esm;
+          elif test "$m" = umd; then
+            # Test importing UMD as both CommonJS and ESM
+            test_import_cjs;
+            test_import_esm;
           else
-            # Test importing as CommonJS
-            node --input-type=commonjs -e "require('${pkg_name}')";
-            # Test importing CommonJS module but allow it to fail
-            node --input-type=module -e "import '${pkg_name}'" || true;
+            # Test importing others as both CommonJS and ESM, but allow ESM to fail
+            test_import_cjs;
+            test_import_esm || true;
           fi
           set +x;
+
           cd /;
           rm -rf "${_tmp}";
